### ISSUE TITLE
number of classes in vulerability risk map

### ISSUE THREAD

**Issue by Tirtha19** [ClarkCGA/UDef-ARP#29]
Hello,

I'm working with 100m resolution input raster datasets to generate risk maps. After processing, I obtained risk map classes ranging from 0 to 100 during both the calibration and confirmation phases. Is this acceptable? Given that risk map classes typically range from 0 to 30 for 30m resolution, shouldn't the number of classes decrease rather than increase to 100 when using a 100m resolution input raster?

**Comment by Tirtha19** [comment]
Hello,
Thanks for the prompt response. I could share my data, however these are classified so is there a way to share them in a manner where others could not get access to them?

Thank you.

**Comment by agcopenhaver** [comment]
Hi @Tirtha19 - please do not share any classified data.

The number of risk classes is hard-coded, and can't be modified in the GUI, so I'm not totally clear how you're getting 100 risk classes. Can you please describe your input distance to forest edge data in more detail or share an unclassified proxy dataset that is representative of your actual data?

Thanks.

**Comment by Tirtha19** [comment]
Hello,
Thanks for suggesting that. I am attaching dummy datasets where I face similar issues. Additionally, I am facing following issues and queries as well:

1. There is no output for the "Predicted CNF Density Map" in the step 2 (Allocated Risk Mapping) of Testing Stage: Prediction Phase.

Could you run my datasets and suggest me corrections to get desired outputs?

[github datasets.zip](https://github.com/user-attachments/files/16619219/github.datasets.zip)

**Comment by agcopenhaver** [comment]
Hi @Tirtha19.

Your data has helped us to identify a minor bug in our code, that appears to be causing your issues, which I will fix in an upcoming PR.

Please do note that we don't always necessarily have 30 classes, but instead have up to 30 classes, numbered between 1 and 30.

**Comment by Tirtha19** [comment]
Hello,
Thanks for figuring out the issue. Should I update the code of vulnerability_map.py as below, to get the desired output?

```python
 # The lower limit of the highest class = spatial resolution (the minimum distance possible without being in non-forest) 
 LL = int(in_ds.GetGeoTransform()[1]) 
  
 self.progress_updated.emit(10) 
 # The upper limit of the lowest class = the Negligible Risk Threshold 
 UL = NRT = int(NRT) 
 n_classes = int(n_classes) 
  
 # Calculate common ratio(r)=(LLmax/LLmin)^1/n_classes 
 r = np.power(LL / UL, 1/n_classes) 
  
 # Create 2D class_array for the areas within the NRT 
 class_array = np.array([[i, i + 1] for i in range(n_classes)]) 
  
 # Calculate UL and LL value for the areas within the NRT 
risk_class[n_classes-1][1] = LL
risk_class[0][0] = NRT
```

**Comment by agcopenhaver** [comment]
Hi Tirtha - I believe that's a separate issue due to your deforestation data containing values that aren't limited to zero and one. 

This is fixable in the code, and I've got a fix already, but want to get my open PR merged before I open another.

For now, please make sure that your deforestation maps are only 0s and 1s. Yours use a nodata value of 3, which is throwing it off.

**Comment by Tirtha19** [comment]
Hello,
I see the issue is no data value. Thanks for identifying that, however, when setting nodata value as 255 or any other number it poses the same issue. How do I treat no data value in this case?
