### ISSUE TITLE
Unit (ha/pixel/year) for the final allocation output

### ISSUE THREAD

**Issue by Tirtha19** [ClarkCGA/UDef-ARP#36]
Hello,
I need to confirm a simple thing.

The final output unit for allocation is in ha/pixel/year. Since I ran zonal statistics using the sum function for my project areas, the sum value should now represent the projected allocation in ha/year, correct?

Thanks.

**Comment by agcopenhaver** [comment]
If you've done everything up to that point correctly, yes, that's correct.
